name: Elixir CI

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    if: ${{ github.event_name != 'pull_request' || !startsWith(github.head_ref, 'release-please--') }}
    uses: leandrocp/github-actions/.github/workflows/elixir-test.yml@main
    with:
      env_vars: '{"MDEX_BUILD": "1"}'

  lint:
    if: ${{ github.event_name != 'pull_request' || !startsWith(github.head_ref, 'release-please--') }}
    uses: leandrocp/github-actions/.github/workflows/elixir-lint.yml@main
    with:
      env_vars: '{"MDEX_BUILD": "1"}'
