name: Publish

on:
  push:
    tags: ["v*"]
  workflow_dispatch:

jobs:
  nif-release:
    uses: leandrocp/github-actions/.github/workflows/nif-release.yml@main
    with:
      project-name: comrak_nif
      project-dir: native/comrak_nif

  hex-publish:
    needs: nif-release
    if: startsWith(github.ref, 'refs/tags/v')
    uses: leandrocp/github-actions/.github/workflows/hex-publish.yml@main
    with:
      env-vars: '{"MDEX_BUILD":"1"}'
      install-rust: true
      pre-publish-command: mix rustler_precompiled.download MDEx.Native --all --print
    secrets:
      HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
